In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('balance.txt', delim_whitespace=True)

Write the code needed to produce a report that provides the following information:
* Compare the average income based on ethnicity. 
* On average, do married or single people have a higher balance?
* What is the highest income in our dataset?
* What is the lowest income in our dataset?
* How many cards do we have recorded in our dataset? (Hint: use `sum()`)
* How many females do we have information for vs how many males? (Hint: use `count()`For a list of all methods for computation of descriptive stats, explore the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).

In [4]:
# Compares the average income based on ethnicity
df.groupby(['Ethnicity'])['Income'].mean()

Ethnicity
African American    47.682101
Asian               44.187833
Caucasian           44.521945
Name: Income, dtype: float64

In [5]:
# Returns information on who have higher balance, married or single people
if df[df.Married == 'Yes'].loc[:,'Balance'].mean() > df[df.Married == 'No'].loc[:,'Balance'].mean():
    print('On average married couples have higher balance, in sum of', df[df.Married == 'Yes'].loc[:,'Balance'].mean(),'.')
else:
    print('On average single people have a higher balance, in sum of', df[df.Married == 'No'].loc[:,'Balance'].mean(),'.')

On average single people have a higher balance, in sum of 13.493509015134242 .

In [6]:
# Returns highest income in the dataset
print('The highest income in our dataset is',df.loc[:,'Income'].max(),'.')

The highest income in our dataset is 186.634 .

In [7]:
# Returns lowest income in the dataset
print('The lowest income in our dataset is',df.loc[:,'Income'].min(),'.')

The lowest income in our dataset is 10.354 .

In [8]:
# Returns amount of cards recorded in the dataset
print('We have recorded', df.loc[:, 'Cards'].sum(), 'cards in our dataset.')

We have recorded 1183 cards in our dataset.

In [9]:
# Returns amount of females and males in the dataset
print('Males vs females - amount of entries by:\n ', df['Gender'].value_counts())

Males vs females - amount of entries by:
  Gender
Female    207
Male      193
Name: count, dtype: int64